/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dominio.Chat;
import dominio.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.ChatBO;
import negocio.MensajeBO;
import negocio.UsuarioBO;

/**
 * Frame para agregar un nuevo chat
 *
 * @author Jesus Medina (╹ڡ╹ ) ID:00000247527
 */
public class FrmNuevoChat extends javax.swing.JFrame {

    private Usuario usuario;
    private frmChat chatFrm;

    UsuarioBO usuarioBO = new UsuarioBO();
    ChatBO chatBO = new ChatBO();
    MensajeBO mensajeBO = new MensajeBO();

    /**
     * Creates new form FrmNuevoChat
     */
    public FrmNuevoChat() {
        initComponents();
    }

    public FrmNuevoChat(Usuario usuario, frmChat chat) {
        this.usuario = usuario;
        this.chatFrm = chat;
        initComponents();
    }

    // Método para guardar el nuevo chat (ejemplo)
    private void guardarNuevoChat() {
        // Lógica para guardar el nuevo chat
        // Validar que el nombre del chat no esté vacío
        String nombreChat = this.txtNombreChat.getText();
        if (nombreChat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del chat no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si el nombre del chat está vacío
        }

        // Crear el chat con los usuarios
        List<Usuario> usuarios = new ArrayList<>();
        usuarios.add(usuario);
        Chat chat = new Chat(nombreChat, null, usuarios, null);

        try {
            // Supongamos que `usuario` es el objeto Usuario que contiene el ID del usuario actual.
            int idUsuario = usuario.getId(); // Asegúrate de que `getId()` devuelve el ID correcto
            chatBO.insertarChatsinImagenYconUsuario(chat, idUsuario);

            // Actualizar la lista de chats en el objeto usuario
            usuario.getChats().add(chat);

            // Actualizar la tabla de chats
            this.chatFrm.llenarTablaChats();

            // Cerrar el diálogo después de una operación exitosa
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FrmNuevoChat.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocurrio un error al crear el chat: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        System.out.println(usuario);
        System.out.println(usuarioBO.obtenerUsuarioPorId(usuario));
        System.out.println(usuarioBO.obtenerTodosLosUsuarios().get(0));

        // Después de guardar el chat, actualiza la tabla en frmChat
        chatFrm.actualizarChats();

        // Cierra la ventana de nuevo chat
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreChat = new javax.swing.JTextField();
        btnAceptarChat = new javax.swing.JButton();

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(7, 94, 84));
        jLabel10.setText("Domicilio");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Chat");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("Nombre");

        btnAceptarChat.setBackground(new java.awt.Color(0, 51, 102));
        btnAceptarChat.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAceptarChat.setText("Aceptar");
        btnAceptarChat.setBorder(null);
        btnAceptarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtNombreChat, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAceptarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreChat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarChatActionPerformed

        guardarNuevoChat();
    }//GEN-LAST:event_btnAceptarChatActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmNuevoChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmNuevoChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmNuevoChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmNuevoChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmNuevoChat().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarChat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombreChat;
    // End of variables declaration//GEN-END:variables
}
